version: '3.8'

services:
  backend:
    build: ./backend
    container_name: trendzy-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SELLER_EMAIL=${SELLER_EMAIL}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASS=${GMAIL_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    volumes:
      - static_data:/app/app/static
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: trendzy-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  static_data:
